apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  namespace: microservizi-app
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    # IMPORTANTE: Rimuoviamo use-regex e rewrite per Keycloak
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-Port $server_port;
spec:
  ingressClassName: nginx
  rules:
    - host: microservizi.local
      http:
        paths:
          # Keycloak - path semplice senza regex
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: keycloak-service
                port:
                  number: 8080
          # Microservizi con rewrite separato
          - path: /ordini
            pathType: Prefix
            backend:
              service:
                name: ordini-service
                port:
                  number: 8081
          - path: /catalogo
            pathType: Prefix
            backend:
              service:
                name: catalogo-service
                port:
                  number: 8082